version: '3.7'
services:
  tutorial-app:
    image: node:11-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: node index.js
